---
- name: test the config template
  hosts: all
  gather_facts: false
  user: root
  tasks:
    - name: run config template ini
      config_template:
        src: templates/test.ini.j2
        dest: /tmp/rendered-config-template.ini
        config_type: ini
        config_overrides: "{{ config_overrides }}"
    - name: run config template yaml
      config_template:
        src: templates/test.yaml.j2
        dest: /tmp/rendered-config-template.yaml
        config_type: yaml
        config_overrides: "{{ config_overrides }}"
    - name: run config template json
      config_template:
        src: templates/test.json.j2
        dest: /tmp/rendered-config-template.json
        config_type: json
        config_overrides: "{{ config_overrides }}"
  vars:
   things: this is a jina2 var
   config_overrides:
     ah: ha
     section1:
       key1: s1 things
       key2: "s2 {{ things }} replacement var"
       iterator_item:
         - thing1
         - thing2
         - thing3
       dict_item:
         test: things
         test: 123
     section2:
       key1: s2 things
       key2: "s2 {{ things }} replacement var"
     other:
       blah: 9000
     list_op:
       shucks:
         - 9000
         - 9001
         - 9002
     DEFAULT:
       f: 22
     default2:
       a: 1
